// console.log(true + false);
// console.log(12 / "6");
// console.log("number" + 15 + 3);
// console.log(15 + 3 + "number");
// console.log("foo" + + "bar");
// console.log('true' == true);
// console.log(false == 'false');
// console.log(null == '');
// console.log(!!"false" == !!"true");
// console.log()  ['x'] == 'x');
// console.log()  [] + null + 1);
// console.log()  [1,2,3] == [1,2,3]);
